#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

CT_SETTINGSPATH="${CONFIG_DIR}/comictagger" && export CT_SETTINGSPATH

redirect_cmd() {
    if [[ "${DEBUG}" == "yes" ]]; then
        "$@"
    else
        "$@" > /dev/null 2>&1
    fi
}

# shellcheck disable=SC2086
redirect_cmd exec s6-setuidgid hotio python3 "${APP_DIR}/Mylar.py" --nolaunch --datadir "${CONFIG_DIR}/app" ${ARGS}
