#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

# shellcheck disable=SC2086
exec s6-setuidgid hotio python3 "${APP_DIR}/Mylar.py" --nolaunch --datadir "${CONFIG_DIR}/app" ${ARGS}
