#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/app/config.ini" ]]; then
    echo "[Git]" > "${CONFIG_DIR}/app/config.ini"
    echo "git_branch = master" >> "${CONFIG_DIR}/app/config.ini"
    chown hotio:hotio "${CONFIG_DIR}/app/config.ini"
fi
